language: java
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - python2.7
before_script:
- unset _JAVA_OPTIONS
script:
- bash deploy.sh
deploy:
  provider: releases
  api_key:
    secure: GITHUB_TOKEN
  file_glob: true
  file:
  - mipay-*.zip
  - eufix-*.zip
  - weather-*.apk
  overwrite: true
  skip_cleanup: true
  on:
    tags: true
